Cleanup provision for windows

diff --git a/eng/pipelines/common/provision.yml b/eng/pipelines/common/provision.yml
--- a/eng/pipelines/common/provision.yml
+++ b/eng/pipelines/common/provision.yml
@@ -23,164 +23,152 @@ steps:
       CleanseAgentToolsDotNet: true           # Cleanse all .NET versions under the agent tools directory and use only those provisioned by the pipeline
       SelfHealPowerShell: false
       AUTH_TOKEN_GITHUB_COM: $(github--pat--vs-mobiletools-engineering-service2)
-  # Provision Xcode
-  - ${{ if ne(parameters.skipXcode, 'true') }}:
-    - task: xamops.azdevex.provisionator-task.provisionator@2
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      displayName: 'Provision Xcode'
-      inputs:
-        provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorXCodePath }}
-        provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
-        github_token: ${{ parameters.gitHubToken }}
-      env:
-        PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
-  # Provision Additional Software
-  - ${{ if ne(parameters.skipProvisioning, 'true') }}:
-    - task: xamops.azdevex.provisionator-task.provisionator@2
-      displayName: 'Provision Additional Software'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      continueOnError: true 
-      inputs:
-        provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorPath }}
-        provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
-        github_token: ${{ parameters.gitHubToken }}
-      env:
-        PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
 
-  # Setup SDK Paths
-  - bash: |
-      echo "##vso[task.prependpath]/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
-      echo "##vso[task.prependpath]~/Library/Developer/Xamarin/android-sdk-macosx"
-    displayName: 'Setup SDK Paths'
-    condition: and(succeeded(), ne(variables['osx2019VmPool'], 'Azure Pipelines'), eq(variables['Agent.OS'], 'Darwin'))
-  # Setup JDK Paths
-  - bash: |
-      echo "##vso[task.setvariable variable=JI_JAVA_HOME]$(JAVA_HOME_11_X64)"
-      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
-    displayName: 'Setup JDK Paths'
-    condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-  # Configure VS Mac for Xcode
-  - bash: |
-      set -x
-      mkdir -p ~/Library/Preferences/Xamarin
-      rm -f ~/Library/Preferences/Xamarin/Settings.plist
-      /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
-      cat ~/Library/Preferences/Xamarin/Settings.plist || true
-    displayName: 'Configure Visual Studio'
-    condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
+  - ${{ if eq(variables['Agent.OS'], 'Darwin') }}:
+    # Provision Xcode
+    - ${{ if ne(parameters.skipXcode, 'true') }}:
+      - task: xamops.azdevex.provisionator-task.provisionator@2
+        displayName: 'Provision Xcode'
+        inputs:
+          provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorXCodePath }}
+          provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
+          github_token: ${{ parameters.gitHubToken }}
+        env:
+          PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
+    # Provision Additional Software
+    - ${{ if ne(parameters.skipProvisioning, 'true') }}:
+      - task: xamops.azdevex.provisionator-task.provisionator@2
+        displayName: 'Provision Additional Software'
+        continueOnError: true 
+        inputs:
+          provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorPath }}
+          provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
+          github_token: ${{ parameters.gitHubToken }}
+        env:
+          PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
 
+    # Setup SDK Paths
+    - bash: |
+        echo "##vso[task.prependpath]/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
+        echo "##vso[task.prependpath]~/Library/Developer/Xamarin/android-sdk-macosx"
+      displayName: 'Setup SDK Paths'
+      condition: and(succeeded(), ne(variables['osx2019VmPool'], 'Azure Pipelines'))
+
+    # Setup JDK Paths
+    - bash: |
+        echo "##vso[task.setvariable variable=JI_JAVA_HOME]$(JAVA_HOME_11_X64)"
+        echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
+      displayName: 'Setup JDK Paths'
+
+    # Configure VS Mac for Xcode
+    - bash: |
+        set -x
+        mkdir -p ~/Library/Preferences/Xamarin
+        rm -f ~/Library/Preferences/Xamarin/Settings.plist
+        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
+        cat ~/Library/Preferences/Xamarin/Settings.plist || true
+      displayName: 'Configure Visual Studio'
   
-  - ${{ if eq(parameters.useOldCertsTasks, 'true') }}:
-    - task: InstallAppleProvisioningProfile@1
-      displayName: 'Install the iOS provisioning profile'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      inputs:
-        provProfileSecureFile: 'Components iOS Provisioning.mobileprovision'
-    - task: InstallAppleProvisioningProfile@1
-      displayName: 'Install the macOS provisioning profile'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      inputs:
-        provProfileSecureFile: 'Components Mac Provisioning.mobileprovision'
-    - task: InstallAppleProvisioningProfile@1
-      displayName: 'Install the tvOS provisioning profile'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      inputs:
-        provProfileSecureFile: 'Components tvOS Provisioning.mobileprovision'
-    - task: InstallAppleCertificate@2
-      displayName: 'Install the iOS certificate'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      inputs:
-        certSecureFile: 'Components iOS Certificate.p12'
-    - task: InstallAppleCertificate@2
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
-      displayName: 'Install the macOS certificate'
-      inputs:
-        certSecureFile: 'Components Mac Certificate.p12'
-  - ${{ if and(eq(parameters.useOldCertsTasks, 'false'), eq(variables['Agent.OS'], 'Darwin')) }}:
-     # Install Certificates and Provisioning Profiles
-    - template: install-certificates.yml@yaml-templates
-      parameters:
-        DeveloperIdApplication: $(developer-id-application)
-        DeveloperIdInstaller: $(developer-id-installer)
-        IphoneDeveloper: $(iphone-developer)
-        MacDeveloper: $(mac-developer)
-        HostedMacKeychainPassword: ${{ parameters.keyringPass }}
+    - ${{ if eq(parameters.useOldCertsTasks, 'true') }}:
+      - task: InstallAppleProvisioningProfile@1
+        displayName: 'Install the iOS provisioning profile'
+        inputs:
+          provProfileSecureFile: 'Components iOS Provisioning.mobileprovision'
+      - task: InstallAppleProvisioningProfile@1
+        displayName: 'Install the macOS provisioning profile'
+        inputs:
+          provProfileSecureFile: 'Components Mac Provisioning.mobileprovision'
+      - task: InstallAppleProvisioningProfile@1
+        displayName: 'Install the tvOS provisioning profile'
+        inputs:
+          provProfileSecureFile: 'Components tvOS Provisioning.mobileprovision'
+      - task: InstallAppleCertificate@2
+        displayName: 'Install the iOS certificate'
+        inputs:
+          certSecureFile: 'Components iOS Certificate.p12'
+      - task: InstallAppleCertificate@2
+        displayName: 'Install the macOS certificate'
+        inputs:
+          certSecureFile: 'Components Mac Certificate.p12'
+    - ${{ if and(eq(parameters.useOldCertsTasks, 'false'), eq(variables['Agent.OS'], 'Darwin')) }}:
+      # Install Certificates and Provisioning Profiles
+      - template: install-certificates.yml@yaml-templates
+        parameters:
+          DeveloperIdApplication: $(developer-id-application)
+          DeveloperIdInstaller: $(developer-id-installer)
+          IphoneDeveloper: $(iphone-developer)
+          MacDeveloper: $(mac-developer)
+          HostedMacKeychainPassword: ${{ parameters.keyringPass }}
       
+  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
+    # Prepare Windows
+    - powershell: |
+        if (-not $(where.exe pwsh)) {
+          $url = "https://github.com/PowerShell/PowerShell/releases/download/v$env:POWERSHELL_VERSION/PowerShell-$env:POWERSHELL_VERSION-win-x64.msi"
+          $output = "$env:TEMP\PowerShell.msi"
+          Remove-Item -Force $output -ErrorAction Ignore
+          Invoke-WebRequest -Uri $url -OutFile $output
+          msiexec.exe /package $output /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1
+        }
+      displayName: 'Install PowerShell Core'
+    
+    - ${{ if ne(parameters.skipVS, 'true') }}:
+      - task: xamops.azdevex.provisionator-task.provisionator@2
+        displayName: 'Provision Visual Studio'
+        inputs:
+          provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorVSPath }}
+          provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
+          github_token: ${{ parameters.gitHubToken }}
+        env:
+          PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
+      - pwsh: |
+          $msbuild = "$env:ProgramFiles/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/MSBuild.exe"
+          echo "##vso[task.setvariable variable=MSBUILD_EXE]$msbuild"
+        displayName: 'Setup MSBuild Paths'
+      
+    # Provision Additional Software
+    - ${{ if ne(parameters.skipProvisioning, 'true') }}:
+      - task: xamops.azdevex.provisionator-task.provisionator@2
+        displayName: 'Provision Additional Software'
+        inputs:
+          provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorPath }}
+          provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
+          github_token: ${{ parameters.gitHubToken }}
+        env:
+          PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
 
-  # Prepare Windows
-  - powershell: |
-      if (-not $(where.exe pwsh)) {
-        $url = "https://github.com/PowerShell/PowerShell/releases/download/v$env:POWERSHELL_VERSION/PowerShell-$env:POWERSHELL_VERSION-win-x64.msi"
-        $output = "$env:TEMP\PowerShell.msi"
-        Remove-Item -Force $output -ErrorAction Ignore
-        Invoke-WebRequest -Uri $url -OutFile $output
-        msiexec.exe /package $output /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1
-      }
-    displayName: 'Install PowerShell Core'
-    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
-
-  - ${{ if ne(parameters.skipVS, 'true') }}:
-    - task: xamops.azdevex.provisionator-task.provisionator@2
-      displayName: 'Provision Visual Studio'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
-      inputs:
-        provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorVSPath }}
-        provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
-        github_token: ${{ parameters.gitHubToken }}
-      env:
-        PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
     - pwsh: |
-        $msbuild = "$env:ProgramFiles/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/MSBuild.exe"
-        echo "##vso[task.setvariable variable=MSBUILD_EXE]$msbuild"
-      displayName: 'Setup MSBuild Paths'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
-
-  # Provision Additional Software
-  - ${{ if ne(parameters.skipProvisioning, 'true') }}:
-    - task: xamops.azdevex.provisionator-task.provisionator@2
-      displayName: 'Provision Additional Software'
-      condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
-      inputs:
-        provisioning_script: ${{ parameters.checkoutDirectory }}/${{ parameters.provisionatorPath }}
-        provisioning_extra_args: ${{ parameters.provisionatorExtraArguments }}
-        github_token: ${{ parameters.gitHubToken }}
-      env:
-        PROVISIONATOR_CHANNEL: ${{ parameters.provisionatorChannel }}
-
-  - pwsh: |
-      if ($env:JAVA_HOME_11_X64) {
-        $env:JAVA_HOME = $env:JAVA_HOME_11_X64
-      } else {
-        $path = (Get-ChildItem $env:ProgramFiles\Microsoft\jdk-11.*\bin\java.exe) | Select-Object -First 1
-        if ($path -and (Test-Path $path)) {
-          $env:JAVA_HOME = $path.Directory.Parent.FullName
-        }
-      }
-      if ($env:JAVA_HOME) {
-        echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME"
-        echo "JAVA_HOME set to '$env:JAVA_HOME'"
-      } else {
-        echo "Unable to set JAVA_HOME"
-      }
-    displayName: 'Setup JDK Paths'
-    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
-
-  - pwsh: |
-      if ($env:ANDROID_SDK_ROOT) {
-        echo "ANDROID_SDK_ROOT already set to '$env:ANDROID_SDK_ROOT'"
-      } else {
-        if ((Test-Path "${env:ProgramFiles(x86)}\Android\android-sdk")) {
-          $env:ANDROID_SDK_ROOT = "${env:ProgramFiles(x86)}\Android\android-sdk"
-        }
-        if ($env:ANDROID_SDK_ROOT) {
-          echo "##vso[task.setvariable variable=ANDROID_SDK_ROOT]$env:ANDROID_SDK_ROOT"
-          echo "ANDROID_SDK_ROOT set to '$env:ANDROID_SDK_ROOT'"
+        if ($env:JAVA_HOME_11_X64) {
+          $env:JAVA_HOME = $env:JAVA_HOME_11_X64
         } else {
-          echo "Unable to set ANDROID_SDK_ROOT"
+          $path = (Get-ChildItem $env:ProgramFiles\Microsoft\jdk-11.*\bin\java.exe) | Select-Object -First 1
+          if ($path -and (Test-Path $path)) {
+            $env:JAVA_HOME = $path.Directory.Parent.FullName
+          }
         }
-      }
-    displayName: 'Setup ANDROID_SDK_ROOT Paths'
-    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
+        if ($env:JAVA_HOME) {
+          echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME"
+          echo "JAVA_HOME set to '$env:JAVA_HOME'"
+        } else {
+          echo "Unable to set JAVA_HOME"
+        }
+      displayName: 'Setup JDK Paths'
+
+    - pwsh: |
+        if ($env:ANDROID_SDK_ROOT) {
+          echo "ANDROID_SDK_ROOT already set to '$env:ANDROID_SDK_ROOT'"
+        } else {
+          if ((Test-Path "${env:ProgramFiles(x86)}\Android\android-sdk")) {
+            $env:ANDROID_SDK_ROOT = "${env:ProgramFiles(x86)}\Android\android-sdk"
+          }
+          if ($env:ANDROID_SDK_ROOT) {
+            echo "##vso[task.setvariable variable=ANDROID_SDK_ROOT]$env:ANDROID_SDK_ROOT"
+            echo "ANDROID_SDK_ROOT set to '$env:ANDROID_SDK_ROOT'"
+          } else {
+            echo "Unable to set ANDROID_SDK_ROOT"
+          }
+        }
+      displayName: 'Setup ANDROID_SDK_ROOT Paths'
 
   # Prepare Both
   - task: UseDotNet@2                 # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops
