delete all simulator runtimes if failing to install one

diff --git a/eng/pipelines/common/provision.yml b/eng/pipelines/common/provision.yml
--- a/eng/pipelines/common/provision.yml
+++ b/eng/pipelines/common/provision.yml
@@ -89,7 +89,21 @@ steps:
       # if we're using Xcode 26.0[.?], then explicitly install the iOS 26.0 simulator (the iOS 26.0.1 simulator doesn't work for us)
       # also install the universal simulator version, so that this bot can run x64 apps in the simulator.
       if [[ "$(REQUIRED_XCODE)" =~ ^26[.]0.*$ ]]; then
-        sudo xcodebuild -downloadPlatform iOS -architectureVariant universal -buildVersion 26.0
+        if ! sudo xcodebuild -downloadPlatform iOS -architectureVariant universal -buildVersion 26.0; then
+          echo "Failed to install simulator runtime, deleting all simulator runtimes and trying again..."
+          sudo xcrun simctl runtime delete all
+          # simulator runtimes are deleted asynchronously, so wait until they're all gone (but max 60 seconds)
+          for i in $(seq 1 60); do
+            sleep 1
+            C=$(xcrun simctl runtime list -j | jq '. | length')
+            if [[ $C == 0 ]]; then
+              echo "    still $C simulators left..."
+              break
+            fi
+          done
+          echo "Re-trying simulator runtime installation"
+          sudo xcodebuild -downloadPlatform iOS -architectureVariant universal -buildVersion 26.0
+        fi
       else
         sudo xcodebuild -downloadPlatform iOS -architectureVariant universal
       fi
