Update setup-jdk.yml

diff --git a/eng/pipelines/common/setup-jdk.yml b/eng/pipelines/common/setup-jdk.yml
--- a/eng/pipelines/common/setup-jdk.yml
+++ b/eng/pipelines/common/setup-jdk.yml
@@ -5,15 +5,21 @@ parameters:
 steps:
 # Setup JDK Paths (gradle needs it)
 - bash: |
-    jdkPath=$(/usr/libexec/java_home -V 2>&1 | grep -E "${{ parameters.jdkMajorVersion }}.jdk" | head -n 1 | awk '{print $NF}')
-    if [ -n "$jdkPath" ]; then
-      echo "##vso[task.setvariable variable=JI_JAVA_HOME]$jdkPath"
-      echo "##vso[task.setvariable variable=JAVA_HOME]$jdkPath"
-      echo "JAVA_HOME set to '$jdkPath'"
+    if [ -n "${{ parameters.jdkFolder }}" ]; then
+      jdkPath="${{ parameters.jdkFolder }}"
+      echo "Using provided JDK folder: $jdkPath"
     else
-      echo "Unable to find JDK ${{ parameters.jdkMajorVersion }}"
-      exit 1
+      jdkPath=$(/usr/libexec/java_home -V 2>&1 | grep -E "${{ parameters.jdkMajorVersion }}.jdk" | head -n 1 | awk '{print $NF}')
+      if [ -n "$jdkPath" ]; then
+        echo "Found JDK path: $jdkPath"
+      else
+        echo "Unable to find JDK ${{ parameters.jdkMajorVersion }}"
+        exit 1
+      fi
     fi
+    echo "##vso[task.setvariable variable=JI_JAVA_HOME]$jdkPath"
+    echo "##vso[task.setvariable variable=JAVA_HOME]$jdkPath"
+    echo "JAVA_HOME set to '$jdkPath'"
   displayName: Setup JDK ${{ parameters.jdkMajorVersion }} Paths
   condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))
 
@@ -31,6 +37,7 @@ steps:
       echo "JAVA_HOME set to '$env:JAVA_HOME'"
     } else {
       echo "Unable to set JAVA_HOME"
+      exit 1
     }
   displayName: Setup JDK ${{ parameters.jdkMajorVersion }} Paths
   condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
